name: Trigger auto deployment for s2c-cb-myapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/s2c-cb-myapp2-AutoDeployTrigger-52489985-aafe-4360-ab56-34fc37a0552e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.S2CCBMYAPP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.S2CCBMYAPP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.S2CCBMYAPP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@ecc33566f4fffe724c058129e9760a68c5c43ad2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.S2CCBMYAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.S2CCBMYAPP2_REGISTRY_PASSWORD }}
          containerAppName: s2c-cb-myapp2
          resourceGroup: kokelowo-containers
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


