name: Trigger auto deployment for s2c-cb-south-existing-env-myapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/s2c-cb-south-existing-env-myapp2-AutoDeployTrigger-164b1789-ab68-4f24-98fa-e9635a1c9ea3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.S2CCBSOUTHEXISTINGENVMYAPP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.S2CCBSOUTHEXISTINGENVMYAPP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.S2CCBSOUTHEXISTINGENVMYAPP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@a27cb86c082be375a4529006f4743dd55037e256
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.S2CCBSOUTHEXISTINGENVMYAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.S2CCBSOUTHEXISTINGENVMYAPP2_REGISTRY_PASSWORD }}
          containerAppName: s2c-cb-south-existing-env-myapp2
          resourceGroup: kokelowo-containers
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


